"""
label_filter.py  —  Stage 3
----------------------------
Uses an LLM to filter all Neo4j node labels down to the subset relevant
to the user query, ranked from most to least important.

Input  : query, all_labels, schema, node_properties
Output : list[dict]  — [{"name": "LABEL", "reason": "..."}, ...]
"""
from _future_ import annotations

import json
import logging
import time

from openai import AzureOpenAI, RateLimitError, APIConnectionError, APIError

from config import AZURE_KEY, AZURE_VERSION, AZURE_ENDPOINT, AZURE_MODEL

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Prompt
# ---------------------------------------------------------------------------

LABEL_PROMPT = """\
You are a graph database assistant for UPL — an agrochemical company.

Domain context:
  This is UPL's internal macroeconomic knowledge graph. ACTIVE_INGREDIENT is the
  central entity around which everything else revolves. Active ingredients are the
  chemical compounds found in crop-protection products (herbicides, fungicides,
  insecticides, etc.) and they are the PRIMARY goods that are traded, exported,
  and imported in this graph.

  The other node types exist to describe the ecosystem around active ingredients:
    - BRAND    : commercial products sold by UPL that contain active ingredients.
    - COMMODITY: crops or raw materials that are either used to synthesise an
                 active ingredient, or that are treated by it in the field.
    - COUNTRY  : nations that export or import active ingredients. Trade-flow
                 relationships connect countries directly to active ingredients.
    - CURRENCY : currencies used by those countries in international trade.
    - NEWS     : articles or reports that reference active ingredients, brands,
                 commodities, countries, or currencies via MENTIONS_* relationships.
                 Include when the query asks about news, coverage, or media mentions.
    - ALERT    : alerts generated by UPL's commodity alert system, connected to
                 commodities via AFFECTS_COMMODITY. Properties: severity, status,
                 alert_type, title, created_at. Include when the query asks about
                 alerts, warnings, risk signals, or notifications related to
                 commodities. Always pair with COMMODITY since that is the connected
                 node.

  Critical insight for label selection:
    In this graph, "goods and services" = active ingredients (and secondarily
    brands and commodities). Any query about trade, import/export, supply chain,
    market access, pricing, or economics ultimately involves ACTIVE_INGREDIENT
    because that is what is being bought, sold, and moved across borders.
    Do NOT treat COMMODITY, COUNTRY, or CURRENCY as sufficient answers to a
    trade query without explicitly reasoning about whether ACTIVE_INGREDIENT
    is also relevant — in almost every case it will be.
    Similarly, include NEWS only when the user's query explicitly asks about
    news, articles, mentions, or media coverage — do not include it for
    standard trade or ingredient queries.

Your task:
  Given a user query, a list of node labels, the relationship schema, and the
  node property catalogue, return ONLY a JSON object with a single key "labels"
  whose value is a list of objects, each with:
    - "name"   : the label string
    - "reason" : one concise sentence explaining why it is relevant to the query

  The list MUST be ordered from most relevant to least relevant.

  Rules (apply in order):
    1. ANCHOR RULE — Always include ACTIVE_INGREDIENT when the query touches
       trade, import/export, supply chain, market, pricing, economics, chemistry,
       or crop protection. It is the anchor of this graph.
    2. Include any label that is directly relevant to the query.
    3. Include any label connected to a relevant label via a meaningful
       relationship in the schema.
    4. Use node properties to resolve ambiguity when label names alone are unclear.
    5. Exclude labels that clearly have nothing to do with the query.
    6. Place the most directly relevant labels first; supporting/contextual
       labels (e.g. CURRENCY) last.
    7. ALERT RULE — Include ALERT (and always pair it with COMMODITY) when the
       query mentions alerts, warnings, risk notifications, severity levels,
       alert status, or alert types. Do NOT include ALERT for standard trade,
       ingredient, or news queries.

Examples:
  Query  : "which brands contain fungicide ingredients?"
  Labels : ["COMMODITY", "CURRENCY", "COUNTRY", "ACTIVE_INGREDIENT", "BRAND", "NEWS"]
  Schema :
    BRAND -[CONTAINS]-> ACTIVE_INGREDIENT
    COUNTRY -[EXPORTS]-> COMMODITY
  Output : {"labels": [
    {"name": "ACTIVE_INGREDIENT", "reason": "Fungicide is a type of active ingredient — the direct subject of the query."},
    {"name": "BRAND",             "reason": "Brands are the products that contain active ingredients."}
  ]}

  Query  : "what are the important topics when talking about import and export of goods?"
  Labels : ["COMMODITY", "CURRENCY", "COUNTRY", "ACTIVE_INGREDIENT", "BRAND", "NEWS"]
  Schema :
    COUNTRY -[EXPORTS]-> ACTIVE_INGREDIENT
    COUNTRY -[IMPORTS]-> ACTIVE_INGREDIENT
    COUNTRY -[EXPORTS]-> COMMODITY
    ACTIVE_INGREDIENT -[USED_IN]-> COMMODITY
  Output : {"labels": [
    {"name": "ACTIVE_INGREDIENT", "reason": "Active ingredients are the primary goods traded across borders in this graph."},
    {"name": "COUNTRY",           "reason": "Countries are the origin and destination nodes for all export/import relationships."},
    {"name": "CURRENCY",          "reason": "Currencies are used by countries to denominate international trade transactions."}
  ]}

  Query  : "what news mentions Glyphosate or India?"
  Labels : ["COMMODITY", "CURRENCY", "COUNTRY", "ACTIVE_INGREDIENT", "BRAND", "NEWS"]
  Schema :
    NEWS -[MENTIONS_ACTIVE_INGREDIENT]-> ACTIVE_INGREDIENT
    NEWS -[MENTIONS_COUNTRY]->           COUNTRY
  Output : {"labels": [
    {"name": "NEWS",              "reason": "The direct subject -- the user is asking for news articles mentioning specific entities."},
    {"name": "ACTIVE_INGREDIENT", "reason": "Glyphosate is an active ingredient explicitly named in the query."},
    {"name": "COUNTRY",           "reason": "India is a country explicitly named in the query."}
  ]}

  Query  : "show me all critical open alerts for commodities"
  Labels : ["COMMODITY", "CURRENCY", "COUNTRY", "ACTIVE_INGREDIENT", "BRAND", "NEWS", "ALERT"]
  Schema :
    ALERT -[AFFECTS_COMMODITY]-> COMMODITY
  Output : {"labels": [
    {"name": "ALERT",     "reason": "The direct subject -- the user is asking for alert nodes filtered by severity and status."},
    {"name": "COMMODITY", "reason": "Commodities are the nodes connected to alerts via AFFECTS_COMMODITY."}
  ]}
"""

# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def get_relevant_labels(
    query: str,
    all_labels: list[str],
    schema: str,
    node_properties: str,
    client: AzureOpenAI | None = None,
) -> list[dict]:
    """
    Filter and rank node labels relevant to query.

    Returns a list of dicts ordered most → least relevant:
        [{"name": "ACTIVE_INGREDIENT", "reason": "..."}, ...]

    Falls back to all labels (unranked, empty reasons) on LLM failure.
    """
    if client is None:
        client = AzureOpenAI(
            api_key        = AZURE_KEY,
            api_version    = AZURE_VERSION,
            azure_endpoint = AZURE_ENDPOINT,
        )

    user_msg = (
        f'Query            : "{query}"\n'
        f'Labels           : {all_labels}\n'
        f'Schema           :\n{schema}\n\n'
        f'Node properties  :\n{node_properties}'
    )

    for attempt in range(1, 4):
        try:
            resp = client.chat.completions.create(
                model           = AZURE_MODEL,
                messages        = [
                    {"role": "system", "content": LABEL_PROMPT},
                    {"role": "user",   "content": user_msg},
                ],
                temperature     = 0,
                response_format = {"type": "json_object"},
            )
            raw     = resp.choices[0].message.content or "{}"
            entries = json.loads(raw).get("labels", [])

            valid = [
                e for e in entries
                if isinstance(e, dict) and e.get("name") in all_labels
            ]
            logger.info("Stage 3 — LLM raw  : %s", raw)
            logger.info("Stage 3 — Ranked   : %s", [e["name"] for e in valid])

            if not valid:
                return [{"name": lbl, "reason": ""} for lbl in all_labels]
            return valid

        except (RateLimitError, APIConnectionError) as exc:
            logger.warning("Stage 3 attempt %d failed: %s — retrying in %ds.", attempt, exc, 2 * attempt)
            time.sleep(2 * attempt)

        except (APIError, Exception) as exc:
            logger.error("Stage 3 error: %s", exc)
            break

    logger.warning("Stage 3 — label filtering failed, falling back to all labels.")
    return [{"name": lbl, "reason": ""} for lbl in all_labels]