"""
relevance_gate.py  —  Stage 1
-------------------------------
Lightweight LLM classifier that determines whether a user query is
answerable from UPL's macroeconomic knowledge graph before any Neo4j
connection or expensive pipeline work is started.

Input  : query (str)
Output : dict — {"relevant": bool, "confidence": float, "reason": str}

  confidence is a float from 0.0 to 1.0 indicating how certain the LLM is
  about its relevant/irrelevant decision. main.py uses this to:
    - Warn the user when a relevant query is borderline (confidence < 0.7)
    - Soften the refusal message when an irrelevant decision is uncertain

If relevant is False, main.py short-circuits and returns a friendly
message without touching Neo4j or running any further LLM calls.
"""
from _future_ import annotations

import json
import logging
import time

from openai import AzureOpenAI, RateLimitError, APIConnectionError, APIError

from config import AZURE_KEY, AZURE_VERSION, AZURE_ENDPOINT, AZURE_MODEL

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Confidence thresholds (used by main.py for display logic)
# ---------------------------------------------------------------------------

CONFIDENCE_HIGH   = 0.8   # green  — clear decision
CONFIDENCE_MEDIUM = 0.6   # yellow — borderline, proceed with caution
# below CONFIDENCE_MEDIUM is considered low (red / uncertain)

# ---------------------------------------------------------------------------
# Prompt
# ---------------------------------------------------------------------------

RELEVANCE_PROMPT = """\
You are a query relevance classifier for UPL's macroeconomic knowledge graph.

The graph contains seven node types:
  - ACTIVE_INGREDIENT : chemical compounds in crop-protection products
                        (herbicides, fungicides, insecticides, etc.)
  - BRAND             : UPL commercial products that contain active ingredients
  - COMMODITY         : crops or raw materials linked to production or usage
                        of active ingredients
  - COUNTRY           : nations that export or import active ingredients,
                        brands, and commodities
  - CURRENCY          : currencies used by those countries in international trade
  - NEWS               : news articles or reports that mention active ingredients,
                         brands, commodities, countries, or currencies
  - ALERT              : commodity alerts generated by UPL's alert system, with
                         properties: severity, status, alert_type, title, id, created_at

Your task:
  Decide whether the user's question can be answered — fully or partially —
  using data from this graph.

  Return ONLY a JSON object with three fields:
    {
      "relevant"   : true | false,
      "confidence" : <float 0.0–1.0>,
      "reason"     : "<one sentence>"
    }

  confidence meaning:
    1.0  — absolutely certain the question is in/out of scope
    0.8  — strongly confident
    0.6  — leaning one way but some ambiguity remains
    0.5  — genuinely uncertain
    0.0  — no idea
  Use values between these anchors proportionally.

  Return relevant=true when the question is about any of:
    - Active ingredients, pesticides, herbicides, fungicides, insecticides
    - Brands or products that contain active ingredients
    - Commodities (crops, raw materials) linked to agrochemicals
    - Countries involved in trade of agrochemicals or commodities
    - Currencies used in that trade
    - Supply chain, import/export, market access, or pricing of agrochemicals
    - Relationships or combinations of the above entities
    - News, articles, or reports that mention agrochemicals, trade, or UPL entities
    - Queries asking what news exists about a specific ingredient, country, or commodity
    - Alerts, warnings, risk signals, or notifications from UPL's commodity alert system
    - Queries about alert severity, status, alert type, or alert history for commodities

  Return relevant=false when the question has no meaningful connection to
  agrochemicals, crop protection, active ingredient trade, or UPL's supply
  chain — even if it mentions a country or currency in an unrelated context.

  Use a lower confidence when:
    - The query is broad/generic and could be partially answered by the graph
    - The query uses domain vocabulary (country, trade) in an unclear context
    - It is genuinely unclear whether the graph models what is being asked

Examples:
  Query  : "which countries import Glyphosate?"
  Output : {"relevant": true,  "confidence": 1.0, "reason": "Directly asks about country-level import relationships for an active ingredient."}

  Query  : "what are the important topics in import and export of goods?"
  Output : {"relevant": true,  "confidence": 0.75, "reason": "Trade and import/export are central to the graph's country-ingredient relationships, though the question is broad."}

  Query  : "which brands contain fungicide active ingredients?"
  Output : {"relevant": true,  "confidence": 1.0, "reason": "Asks about brand-to-active-ingredient relationships, which the graph models directly."}

  Query  : "what commodities does India produce?"
  Output : {"relevant": true,  "confidence": 0.65, "reason": "The graph models country-commodity links for agrochemicals, though not all commodities may be covered."}

  Query  : "what is the capital of France?"
  Output : {"relevant": false, "confidence": 1.0, "reason": "General geography question with no connection to agrochemicals or UPL's supply chain."}

  Query  : "what is the current EUR/USD exchange rate?"
  Output : {"relevant": false, "confidence": 0.9, "reason": "Asks for live market data; currencies in the graph are trade metadata, not live exchange rates."}

  Query  : "tell me a joke"
  Output : {"relevant": false, "confidence": 1.0, "reason": "Entertainment request entirely unrelated to the knowledge graph."}

  Query  : "who is the CEO of UPL?"
  Output : {"relevant": false, "confidence": 1.0, "reason": "Asks about organisational personnel, which the graph does not model."}

  Query  : "how does global trade affect food prices?"
  Output : {"relevant": false, "confidence": 0.55, "reason": "Broad macroeconomic question; the graph captures agrochemical trade flows but not food price data."}

  Query  : "what news mentions Glyphosate?"
  Output : {"relevant": true, "confidence": 1.0, "reason": "Directly asks for news articles referencing a specific active ingredient in the graph."}

  Query  : "any news about countries importing fungicides?"
  Output : {"relevant": true, "confidence": 0.9, "reason": "Asks for news related to agrochemical trade flows, which the graph and news nodes model."}

  Query  : "show me all critical alerts for commodities"
  Output : {"relevant": true, "confidence": 1.0, "reason": "Directly asks for ALERT nodes filtered by severity, which the graph models."}

  Query  : "are there any open alerts related to wheat?"
  Output : {"relevant": true, "confidence": 0.95, "reason": "Asks for ALERT nodes connected to a commodity (wheat) with a status filter."}
"""

# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def check_relevance(
    query: str,
    client: AzureOpenAI | None = None,
    conversation_history: list[dict] | None = None,
) -> dict:
    """
    Classify whether query is answerable from UPL's knowledge graph.

    Returns:
        {
            "relevant"   : bool,
            "confidence" : float,   # 0.0–1.0
            "reason"     : str,
        }

    Failure fallback (fail open):
        {"relevant": True, "confidence": 0.5, "reason": ""}
    """
    if client is None:
        client = AzureOpenAI(
            api_key        = AZURE_KEY,
            api_version    = AZURE_VERSION,
            azure_endpoint = AZURE_ENDPOINT,
        )

    # Inject last turn so ambiguous follow-ups (e.g. "what about France?") pass the gate
    context_prefix = ""
    if conversation_history:
        last = conversation_history[-1]
        context_prefix = f'Previous query: "{last["query"]}"\n\n'
    user_content = f'{context_prefix}Current query: "{query}"'

    for attempt in range(1, 4):
        try:
            resp = client.chat.completions.create(
                model           = AZURE_MODEL,
                messages        = [
                    {"role": "system", "content": RELEVANCE_PROMPT},
                    {"role": "user",   "content": user_content},
                ],
                temperature     = 0,
                response_format = {"type": "json_object"},
                max_tokens      = 150,   # classification only — keep cheap
            )
            raw  = resp.choices[0].message.content or "{}"
            data = json.loads(raw)

            relevant   = bool(data.get("relevant", True))
            confidence = float(max(0.0, min(1.0, data.get("confidence", 0.5))))
            reason     = data.get("reason", "")

            logger.info(
                "Stage 1 — relevant=%s | confidence=%.2f | reason=%s",
                relevant, confidence, reason,
            )
            return {"relevant": relevant, "confidence": confidence, "reason": reason}

        except (RateLimitError, APIConnectionError) as exc:
            logger.warning("Stage 1 attempt %d failed: %s — retrying in %ds.", attempt, exc, 2 * attempt)
            time.sleep(2 * attempt)

        except (APIError, Exception) as exc:
            logger.error("Stage 1 error: %s", exc)
            break

    # Fail open — if the gate itself errors, let the pipeline continue
    logger.warning("Stage 1 — relevance check failed, defaulting to relevant=True.")
    return {"relevant": True, "confidence": 0.5, "reason": ""}